#!/bin/bash
set -euo pipefail

framework="net10.0"

export NUGET_PACKAGES=/root/.nuget/packages

# Create a timestamped results dir that can be mounted from host
timestamp=$(date -u +%Y%m%dT%H%M%SZ)
resultDir="/artifacts/TestResults/$timestamp"
coverageDir="/artifacts/TestResults/CoverageReport/$timestamp"
latestCoverageDir="/artifacts/TestResults/CoverageReport/Latest"
#mkdir -p "${resultDir}/CoverageReport"
mkdir -p "${coverageDir}/Markdown" "${coverageDir}/Html" "${coverageDir}/Cobertura" "${coverageDir}/Badges"

# Configuration (allow override from environment)
CONFIGURATION=${CONFIGURATION:-Development}

# Ensure we're in workspace containing the solution/repo
cd /workspace || exit 1

# Ensure tests use Development environment
export ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}

echo "Discovering test projects..."

# Run dotnet test for each test project found under the repo
exit_code=0

#dotnet clean
#dotnet nuget locals all --clear
dotnet restore || exit_code=$?
dotnet build -c Debug --no-restore || exit_code=$?

if [ $exit_code -ne 0 ]; then
  echo "Build failed with exit code $exit_code"
  exit $exit_code
fi

# Find all .Tests.csproj files and run tests
#while IFS= read -r -d '' proj; do
#  name=$(basename "${proj}")
#  name_no_ext="${name%.csproj}"
#  proj_dir=$(dirname "${proj}")
#  echo "Running tests for project: $name_no_ext"
#  echo "dotnet test \"$proj\" -c Debug --results-directory \"${resultDir}\" --code-coverage"
#done < <(find . -type f -name "*.Tests.csproj" -print0)

dotnet test -c Debug --results-directory "${resultDir}" --collect:"XPlat Code Coverage" --logger "trx" || exit_code=$?

if [ $exit_code -ne 0 ]; then
  echo "Some tests failed with exit code $exit_code"
  exit $exit_code
fi

# After running tests try to merge coverage reports into a single file and generate an HTML report
echo "Combining coverage reports (results in: ${resultDir})..."

# Find all coverage.cobertura.xml files generated by dotnet test
mapfile -t coverage_files < <(find "${resultDir}" -type f -name "coverage.cobertura.xml")

if [ "${#coverage_files[@]}" -gt 0 ]; then
  echo "Found coverage files. Generating combined report..."

  rm -rf "${latestCoverageDir}"

  # Generate HTML and Cobertura combined report
  reportgenerator -reports:"${resultDir}/**/coverage.cobertura.xml" -targetdir:"${latestCoverageDir}" -reporttypes:"Cobertura" -title:"TirsvadWeb Portfolio - coverage report" || echo "reportgenerator failed"
  reportgenerator -reports:"${resultDir}/**/coverage.cobertura.xml" -targetdir:"${latestCoverageDir}/Html" -reporttypes:"Html_Dark" -title:"TirsvadWeb Portfolio - coverage report" || echo "reportgenerator failed"
  reportgenerator -reports:"${resultDir}/**/coverage.cobertura.xml" -targetdir:"${latestCoverageDir}/Markdown" -reporttypes:"Markdown" -title:"TirsvadWeb Portfolio - coverage report" || echo "reportgenerator failed"
  reportgenerator -reports:"${resultDir}/**/coverage.cobertura.xml" -targetdir:"${latestCoverageDir}/Badges" -reporttypes:"Badges" -title:"TirsvadWeb Portfolio coverage report" || echo "reportgenerator failed"
else
  echo "No coverage files found in ${resultDir}"
fi

echo "Test results and coverage reports are available in /artifacts/TestResults/"

exit $exit_code
