// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.Data;

#nullable disable

namespace Portfolio.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20250614082256_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Portfolio.Core.Models.Genre", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("e3642c4e-db08-47fa-8757-5a62ada67edb"),
                            Name = "Python"
                        },
                        new
                        {
                            Guid = new Guid("a5ab66c1-30d9-4773-8366-dad834af6bbd"),
                            Name = "c#"
                        },
                        new
                        {
                            Guid = new Guid("0936dd59-5f27-4efd-b415-05f0bb817ee2"),
                            Name = "Blazor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
